
///data for flatlist
const participants = [
    { id: "1", name: "Alice", followed: false },
    { id: "2", name: "Bob", followed: false },
    { id: "3", name: "Charlie", followed: false },
    { id: "4", name: "David", followed: false },
    { id: "5", name: "Eve", followed: false },
    { id: "6", name: "Frank", followed: false },
    { id: "7", name: "Grace", followed: false },
    { id: "8", name: "Hank", followed: false },
    { id: "9", name: "Ivy", followed: false },
    { id: "10", name: "Jack", followed: false },
    { id: "11", name: "Kate", followed: false },
    { id: "12", name: "Leo", followed: false },
    { id: "13", name: "Mia", followed: false },
    { id: "14", name: "Nathan", followed: false },
    { id: "15", name: "Olivia", followed: false },
    { id: "16", name: "Paul", followed: false },
    { id: "17", name: "Quinn", followed: false },
    { id: "18", name: "Rachel", followed: false },
    { id: "19", name: "Steve", followed: false },
    { id: "20", name: "Tina", followed: false },
    { id: "21", name: "Uma", followed: false },
    { id: "22", name: "Victor", followed: false },
    { id: "23", name: "Wendy", followed: false },
    { id: "24", name: "Xander", followed: false },
    { id: "25", name: "Yasmine", followed: false },
    { id: "26", name: "Zane", followed: false },
    { id: "27", name: "Aaron", followed: false },
    { id: "28", name: "Bella", followed: false },
    { id: "29", name: "Chris", followed: false },
    { id: "30", name: "Diana", followed: false },
    { id: "31", name: "Ethan", followed: false },
    { id: "32", name: "Fiona", followed: false },
    { id: "33", name: "George", followed: false },
    { id: "34", name: "Holly", followed: false },
    { id: "35", name: "Ian", followed: false },
    { id: "36", name: "Julia", followed: false },
    { id: "37", name: "Kyle", followed: false },
    { id: "38", name: "Luna", followed: false },
    { id: "39", name: "Mike", followed: false },
    { id: "40", name: "Nina", followed: false },
    { id: "41", name: "Oscar", followed: false },
    { id: "42", name: "Penny", followed: false },
    { id: "43", name: "Ron", followed: false },
    { id: "44", name: "Sophie", followed: false },
    { id: "45", name: "Tom", followed: false },
    { id: "46", name: "Ursula", followed: false },
    { id: "47", name: "Vince", followed: false },
    { id: "48", name: "Willa", followed: false },
    { id: "49", name: "Xena", followed: false },
    { id: "50", name: "Yuri", followed: false },
    { id: "51", name: "Zara", followed: false },
    { id: "52", name: "Alex", followed: false },
    { id: "53", name: "Brian", followed: false },
    { id: "54", name: "Catherine", followed: false },
    { id: "55", name: "Daniel", followed: false },
    { id: "56", name: "Emily", followed: false },
    { id: "57", name: "Felix", followed: false },
    { id: "58", name: "Gloria", followed: false },
    { id: "59", name: "Henry", followed: false },
    { id: "60", name: "Isla", followed: false },
  ];


  export default participants;